/**
 * Order status states matching docs/DATABASE_DESIGN.md
 */
const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAID: 'PAID',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  COMPLETED: 'COMPLETED'
};

module.exports = {
  ORDER_STATUS,
  ALL_ORDER_STATUSES: Object.values(ORDER_STATUS)
};
